[repository]
name = "hyprland-plugins"
authors = ["Vaxry"]
commit_pins = []


[hyprpill]
description = "A plugin to add animated pill grabbers to windows"
authors = ["mylescox"]
output = "hyprpill/hyprpill.so"
build = [
    "make -C hyprpill all",
]

