[hyprpill]
description = "A plugin to add animated pill grabbers to windows"
version = "1.0"
authors = ["mylescox"]

[hyprpill.build]
output = "hyprpill/hyprpill.so"
steps = [
    "make -C hyprpill all",
]

